[build]
  command = ""            # –æ—Ç–∫–ª—é—á–∞–µ–º npm run build
  publish = "public"   # –ø—É—Ç—å –∫ html-—Å—Ç—Ä–∞–Ω–∏—Ü–∞–º

# üîÅ –ü–µ—Ä–µ–Ω–∞–ø—Ä–∞–≤–ª–µ–Ω–∏—è (—á—Ç–æ–±—ã /hire ‚Üí /hire.html –∏ —Ç.–ø.)
[[redirects]]
  from = "/hire"
  to = "/hire.html"
  status = 200

[[redirects]]
  from = "/stealth"
  to = "/stealth.html"
  status = 200

[[redirects]]
  from = "/mapping"
  to = "/mapping.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

 [[headers]]
 for = "/admin/config.yml"
 [headers.values]
 Content-Type = "text/yaml"


