[build]
  publish = "src/pages"
  command = "npm run build || echo 'no build step'"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[functions]
  directory = "src/functions"

[[redirects]]
  from = "/hire"
  to = "/hire.html"
  status = 200

[[redirects]]
  from = "/stealth"
  to = "/stealth.html"
  status = 200

[[redirects]]
  from = "/mapping"
  to = "/mapping.html"
  status = 200
