backend:
  name: git-gateway
  repo: ironbark-pro/ironbark-jd
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/a7dafa0d-146a-4c42-853b-9c0290ad997b/pkce
  auth_token_endpoint: /sites/a7dafa0d-146a-4c42-853b-9c0290ad997b/token
  gateway_url: https://gateway.decapbridge.com

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "jobs"
    label: "Job Listings"
    folder: "jobs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: false
    fields:
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Short Description", name: "intro", widget: "text", required: false }
      - { label: "About the Company", name: "company", widget: "markdown" }
      - { label: "About the Role", name: "role", widget: "markdown" , required: false }
      - { label: "Responsibilities", name: "responsibilities", widget: "markdown" }
      - { label: "Requirements", name: "requirements", widget: "markdown" }
      - { label: "Conditions", name: "conditions", widget: "markdown" }
      - { label: "Posted Date", name: "date", widget: "datetime" }
