backend:
  name: github
  repo: ironbark-pro/ironbark-jd
  branch: m
  ainmedia_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "jobs"
    label: "Job Listings"
    folder: "jobs"
    create: true
    slug: "{{slug}}"
    preview_path: "jobs/{{slug}}.html"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Short Description", name: "intro", widget: "text", required: false }
      - { label: "About the Company", name: "company", widget: "markdown" }
      - { label: "About the Role", name: "role", widget: "markdown" , required: false }
      - { label: "Responsibilities", name: "responsibilities", widget: "markdown" }
      - { label: "Requirements", name: "requirements", widget: "markdown" }
      - { label: "Conditions", name: "conditions", widget: "markdown" }
      - { label: "Posted Date", name: "date", widget: "datetime" }
