backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
media_library:
  name: uploadcare
config:
  publicKey: demopublickey
collections:
  - name: "jobs"
    label: "Job Listings"
    folder: "jobs"
    create: true
    slug: "{{slug}}"
    preview_path: "jobs/{{slug}}.html"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: false}
