backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "src/assets/uploads"

collections:
  - name: "jobs"
    label: "Job Listings"
    folder: "src/pages/jobs"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    editor:
      preview: false
    fields:
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Short Description", name: "intro", widget: "text" }
      - { label: "About the Company", name: "company", widget: "markdown" }
      - { label: "About the Role", name: "role", widget: "markdown" }
      - { label: "Responsibilities", name: "responsibilities", widget: "markdown" }
      - { label: "Requirements", name: "requirements", widget: "markdown" }
      - { label: "Conditions", name: "conditions", widget: "markdown" }
      - { label: "Posted Date", name: "date", widget: "datetime" }
