backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/uploads"
public_folder: "src/assets/uploads"


collections:
  - name: "jobs"
    label: "Job Listings"
    folder: "src/pages/hire"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    editor:
      preview: false
    fields:
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Industry", name: "industry", widget: "string"}
      - {label: "Employment Type", name: "type", widget: "string", default: "Full-time"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Requirements", name: "requirements", widget: "markdown"}
